### ISSUE TITLE
Key Recovery

### ISSUE THREAD

**Issue by ghost** [bakd247/ecdsaKeyFinder#11]
Hi sir,

This tool can recovery the private key but we don't know how much time it may be, example I want to find from public key first **private key:** 1 , coordinates:

**x:** 79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798
**y:** 483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8

and it is running forever and do not find anything. Are there any chance to find that one with hashadder?

**Comment by bakd247** [comment]
I currently have it set to do a random search...
I am working on checking easily countable positions first and adding more functionality with hashAdder.....
try enetering your key into the site link I have on privatekeyfinders page to make sure you key is a secure key...and if that site doesn;t find it then random search is your best bet....
fyi...you can do a multiple list of 100K long now since I added binary search just a few days ago...
make sure your using the latest code I have posted

________________________________
From: dexizer37 ***@***.***>
Sent: Tuesday, March 19, 2024 3:40 AM
To: bakd247/ecdsaKeyFinder ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bakd247/ecdsaKeyFinder] Key Recovery (Issue #11)


Hi sir,

This tool can recovery the private key but we don't know how much time it may be, example I want to find from public key first private key: 1 , coordinates:

x: 79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798
y: 483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8

and it is running forever and do not find anything. Are there any chance to find that one with hashadder?

**Comment by ghost** [comment]
I saw your videos and that is very interesting and I have a one question for easy counting it will be for first example 50000000 or more keys or for all 115792089237316195423570985008687907852837564279074904382605163141518161494337 ?

**Comment by bakd247** [comment]
Single Core Single thread seems to be able to do around 20K per second...so I am planning on a easy count version to be used first that will do groups of 4 billion (2^32) with a specified number of sections that will divide up the entire workspace according to an input number. Also it will give an estimated time until all search space is searched. Then if that version does not find the key first then the random version is to be used.
That will be the last update for the privateKeyFinder tool...
Then I will be working on hashAdder which has the exact same features but uses all multiples and divisors of 2 and 3 and will use multicore and multithreading
